---
# Undo network configuration from the mesh_node role, to reconnect via
# standard wifi settings. Mainly intended to be selectively enabled
# during development; see site.yml for instructions.

- name: remove wlan0 interface
  file:
    path: /etc/network/interfaces.d/wlan0
    state: absent
  become: yes
  become_user: root
  register: remove_network_interface

- name: allow DHCPD to automatically configure wlan0
  lineinfile:
    path: /etc/dhcpcd.conf
    state: absent
    regexp: denyinterfaces wlan0
  become: yes
  become_user: root
  register: allow_dhcpcd_conf

# We want this to run right away, but flush_handlers doesn't play
# nicely with conditional roles.
- name: reboot after changing network config
  reboot:
  when: remove_network_interface.changed or allow_dhcpcd_conf.changed
  become: yes
  become_user: root
