---
- name: check current hostname
  slurp:
    src: '/etc/hostname'
  register: hostname

- name: set a random hostname
  hostname:
    name: "{{ hostname_prefix }}{{ item }}"
  with_random_choice: "{{ hostname_suffixes }}"
  when: ( hostname['content'] | b64decode | trim ) == 'raspberrypi'
  become: yes
  become_user: root

- name: allow access via SSH key
  authorized_key:


- name: set the pi user password
  user:
    name: pi
    password: "{{ encrypted_password }}"
  become: yes
  become_user: root
