---
- name: get current root partition size
  shell: fdisk -l {{ device }}p2 | head -1 | sed 's/.* \(.*\) bytes.*/\1/'
  register: current_root_partition_size
  changed_when: False
  become: yes
  become_user: root

# We're not using the parted module because it will cause boot
# failures, see
# https://raspberrypi.stackexchange.com/questions/68082/why-wont-my-raspberrypi-boot-if-i-use-parted-to-adjust-the-partition.
- name: expand root partition
  shell: "echo ', +{{ expand_root_partition_gb }}G' | sfdisk --force -N 2 {{ device }}"
  when: (current_root_partition_size.stdout | int) < (expand_root_partition_gb + 1) * 1000000000
  notify:
    - reboot system before resize
    - resize root fs
  become: yes
  become_user: root

- name: force root fs resize before continuing
  meta: flush_handlers