---
- name: apply login and hostname configuration
  hosts:
    - bootstrap
  roles:
    - credentials

- name: fully configure a featherstreamer device
  hosts:
    - ungrouped
  roles:
    - expand_root_partition

    # Set featherstreamer_lan=True in the [ungrouped:vars] section of
    # hosts.local if you want to connect using the "standard" wifi
    # setup instead of the ad hoc network.
    - role: lan_node
      when: "featherstreamer_lan | default(False)"
    - role: mesh_node
      when: "not ( featherstreamer_lan | default(False) )"
