---
- name: apply login and hostname configuration
  hosts:
    - bootstrap
  roles:
    - credentials

- name: fully configure a featherstreamer device
  hosts:
    - ungrouped
  roles:
    - expand_root_partition
    - mesh_node
