---
- name: apply preliminary login and hostname configuration
  hosts:
    - bootstrap
  roles:
    - credentials

- name: configure a featherstreamer
  hosts:
    - ungrouped
  # strategy: free
  roles:
    - expand_root_partition
    - access_point
    - featherstreamer
