---
device: /dev/mmcblk0

# i.e. the partition lives at "{{ device }}p{{ root_partition_number }}
root_partition_number: 2

# Note - careful changing this - if you increase it, it may trigger an
# unnecessarily large expansion (see the "expand root partition"
# task).
expand_root_partition_gb: 4

# TODO: Make this smaller at creation, and allow auto-expand on first boot from a distributed image.
data_partition_gb: 6
data_filesystem_label: data

data_filesystem_uid: pi
data_filesystem_gid: pi