---
- name: install dependencies
  apt:
    cache_valid_time: 86400
    name:
      - stow
  become: yes
  become_user: root

- name: get nodejs binaries
  unarchive:
    dest: /usr/local/stow/
    src: "https://nodejs.org/dist/v10.15.3/node-v{{ node_version }}-linux-armv6l.tar.xz"
    remote_src: yes
  become: yes
  become_user: root

- name: check for existing node command
  stat:
    path: /usr/local/bin/node
  register: stat_node

- name: install nodejs
  shell: "stow node-v{{ node_version }}-linux-armv6l"
  args:
    chdir: /usr/local/stow
  changed_when: not stat_node.stat.exists
  become: yes
  become_user: root

- name: make module directory writable by the pi user
  file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
    owner: pi
    group: pi
  become: yes
  become_user: root
  with_items:
    - /usr/local/src/featherstreamer
    # Need to access this directory during rsync
    - /usr/local/src/

- name: copy package-lock.json individually
  copy:
    dest: /usr/local/src/featherstreamer/package-lock.json
    src: "{{ module_location }}/package-lock.json"
  register: copy_package_lock

- name: synchronize module from local sources
  synchronize:
    mode: push
    delete: yes
    dest: /usr/local/src/
    src: "{{ module_location }}"
    rsync_opts:
      - "--exclude='node_modules'"

- name: install node modules
  shell: npm install --production
  args:
    chdir: /usr/local/src/featherstreamer
  when: copy_package_lock.changed